# Generated by Django 6.0.5 on 2026-05-19 20:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('sitio', models.CharField(max_length=100)),
                ('highest_education', models.CharField(choices=[('high_school', 'High School Graduate'), ('college_undergrad', 'College Undergraduate'), ('college_graduate', 'College Graduate'), ('post_graduate', 'Post-Graduate'), ('vocational', 'Vocational Course')], default='college_graduate', max_length=50)),
                ('school_institution', models.CharField(max_length=200)),
                ('year_graduated', models.IntegerField()),
                ('has_criminal_record', models.BooleanField(default=False)),
                ('background_details', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('interview_scheduled', 'Interview Scheduled'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='pending', max_length=30)),
                ('consent_checkbox', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'applicant',
                'verbose_name_plural': 'applicants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicantDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('resume', 'Resume / CV'), ('nbi_clearance', 'NBI Clearance'), ('police_clearance', 'Police Clearance'), ('government_id', 'Government ID'), ('other', 'Other Document')], default='resume', max_length=30)),
                ('file', models.FileField(upload_to='applicants/documents/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applicants.applicant')),
            ],
            options={
                'verbose_name': 'applicant document',
                'verbose_name_plural': 'applicant documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
