# Generated by Django 6.0.5 on 2026-05-19 21:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='sitio',
            field=models.CharField(choices=[('All Season 1', 'All Season 1'), ('All Season 2', 'All Season 2'), ('All Season 3', 'All Season 3'), ('Caimito', 'Caimito'), ('Elma', 'Elma'), ('Laguna 1', 'Laguna 1'), ('Laguna 2', 'Laguna 2'), ('Little Hawaii', 'Little Hawaii'), ('Lourdes Extension', 'Lourdes Extension'), ('Lourdes Proper', 'Lourdes Proper')], default='Lourdes Proper', max_length=100),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['status'], name='applicant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['email'], name='applicant_email_idx'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['last_name', 'first_name'], name='applicant_name_idx'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['-created_at'], name='applicant_created_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantdocument',
            index=models.Index(fields=['applicant', 'document_type'], name='doc_applicant_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='applicantdocument',
            constraint=models.UniqueConstraint(fields=('applicant', 'document_type'), name='unique_applicant_document_type'),
        ),
    ]
