# Generated by Django 6.0.5 on 2026-05-11 09:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('certificate_type', models.CharField(choices=[('barangay_clearance', 'Barangay Clearance'), ('residency', 'Certificate of Residency'), ('indigency', 'Certificate of Indigency'), ('business_permit', 'Certificate of Business Permit'), ('cedula', 'Cedula'), ('low_income', 'Certificate of Low Income'), ('no_income', 'Certificate of No Income'), ('identification', 'Certificate of Identification')], max_length=50)),
                ('purpose', models.TextField(blank=True, help_text='Purpose of the certificate request')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('for_verification', 'For Verification'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('ready_printing', 'Ready for Printing'), ('ready_pickup', 'Ready for Pickup'), ('completed', 'Completed'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('qr_token', models.CharField(blank=True, max_length=64, unique=True)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='requests/qr_codes/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_made', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificate_requests', to='residents.resident')),
            ],
            options={
                'verbose_name': 'certificate request',
                'verbose_name_plural': 'certificate requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
