# Generated by Django 6.0.5 on 2026-05-16 19:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequest',
            name='extra_fields',
            field=models.JSONField(blank=True, default=dict, help_text='Dynamic fields depending on certificate type'),
        ),
        migrations.CreateModel(
            name='CertificateDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Name or type of the document (e.g., 'Valid ID', 'Proof of Residency')", max_length=255)),
                ('file', models.FileField(upload_to='requests/documents/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='certificate_requests.certificaterequest')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
