# Generated by Django 6.0.5 on 2026-06-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_requests', '0002_certificaterequest_extra_fields_certificatedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaterequest',
            name='certificate_type',
            field=models.CharField(choices=[('barangay_clearance', 'Barangay Clearance'), ('residency', 'Certificate of Residency'), ('indigency', 'Certificate of Indigency'), ('cedula', 'Cedula'), ('low_income', 'Certificate of Low Income'), ('no_income', 'Certificate of No Income'), ('business_permit', 'Certificate of Business Permit'), ('identification', 'Certificate of Identification'), ('attestation', 'Attestation'), ('jail_entrance', 'Jail Entrance'), ('solo_parent', 'Solo Parent')], max_length=50),
        ),
    ]
