# Generated by Django 6.0.5 on 2026-05-11 09:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificate_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_type', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('html_template', models.TextField(help_text='HTML template with Django template tags. Available context: resident, request, date, barangay_captain, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'certificate template',
                'verbose_name_plural': 'certificate templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pdf_file', models.FileField(upload_to='certificates/generated/%Y/%m/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('certificate_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_certificates', to='certificate_requests.certificaterequest')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template_used', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificates.certificatetemplate')),
            ],
            options={
                'verbose_name': 'generated certificate',
                'verbose_name_plural': 'generated certificates',
                'ordering': ['-generated_at'],
            },
        ),
    ]
